# SPDX-FileCopyrightText: 2025-2026 Revelation Team
#
# SPDX-License-Identifier: MIT

apiVersion: v1
kind: Service
metadata:
  name: revelation-server
  namespace: default
  labels:
    app: revelation-server
spec:
  selector:
    app: revelation-server
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
